import Head from "next/head";
import DisplayImage from "@/Components/DisplayImage";
import ColorThief from "colorthief";
import { useState, useEffect } from "react";

const gallery = <i className="fas fa-images"></i>;

export default function Home() {

  const [uploadedImage, setUploadedImage] = useState(null);
  const [colorPalette, setColorPalette] = useState(null);
  const [gradient, setGradient] = useState("");

  const uploadImage = (e) => {
    const file = e.target.files[0];
    const reader = new FileReader();

    reader.onload = async (event) => {
      const img = new Image();

      // Ждём, пока картинка загрузится
      img.onload = () => {
        const colorThief = new ColorThief();
        const colorPalette = colorThief.getPalette(img, 6);
        setUploadedImage(event.target.result);
        setColorPalette(colorPalette);
      };
      img.src = event.target.result;
    };

    reader.readAsDataURL(file);
  };

  useEffect(() => {
    if (colorPalette) {
      const gradientColors = colorPalette.map((color) => {
        return `rgb(${color.join(",")})`;
      });

      // Применяем градиент
      setGradient(`linear-gradient(to right, ${gradientColors.join(", ")})`);
    }
  }, [colorPalette]);

  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link
              rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
              integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
              crossOrigin="anonymous"
              referrerPolicy="no-referrer"
          />
        </Head>

        <header>
          <div className="input">
            <label htmlFor="file">{gallery} Upload Image</label>
            <input type="file" id="file" hidden onChange={uploadImage} />
          </div>
        </header>

        <main
            className={'main'}
            style={{
              background: gradient,
            }}
        >
          <DisplayImage
              uploadedImage={uploadedImage}
              colorPalette={colorPalette}
          />
        </main>
      </>
  );
}
